### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by RhanCandia** [AbeYuki/minecraft-bedrock-arm64-docker#1]
Any instructions on how to use this? I tried running this container on Oracle Cloud but  nothing happens.

**Comment by AbeYuki** [comment]
Thanks for the issue.
We have not been able to maintain this repository.
It seems that the server and client versions do not match and cannot connect to the server.
I will push the image corresponding to the client version.
Please give me a little more time.

**Comment by AbeYuki** [comment]
The latest version (1.19.81.01) has been released.
https://github.com/AbeYuki/minecraft-bedrock-arm64-docker/releases

Try running the container on an ARM64 architecture server such as RaspberryPi, M1 Mac, AWS Gravidion, etc.

**Comment by RhanCandia** [comment]
> The latest version (1.19.81.01) has been released. https://github.com/AbeYuki/minecraft-bedrock-arm64-docker/releases
> 
> Try running the container on an ARM64 architecture server such as RaspberryPi, M1 Mac, AWS Gravidion, etc.

Thank you for taking the time updating this. Can you provide a sample docket composer file? Or maybe a list of environment variables? Apologies as docker is still new to me. Thanks.

**Comment by AbeYuki** [comment]
Click here for docker compose.
https://github.com/AbeYuki/minecraft-bedrock-arm64-docker/blob/main/docker-compose.yaml

Also, the Dockerfile does not contain the necessary commands, and it is not a good image because it executes the commands listed in docker compose.
We have fixed it so that the container runs with a new build and no arguments.

It also works with docker run.
```
docker run -itd --rm -p 19132:19132/udp abeyuki/minecraft-bedrock-arm64:1.19.81.01
```

**Comment by RhanCandia** [comment]
> Click here for docker compose. https://github.com/AbeYuki/minecraft-bedrock-arm64-docker/blob/main/docker-compose.yaml
> 
> Also, the Dockerfile does not contain the necessary commands, and it is not a good image because it executes the commands listed in docker compose. We have fixed it so that the container runs with a new build and no arguments.
> 
> It also works with docker run.
> 
> ```
> docker run -itd --rm -e EULA=TRUE -e GAMEMODE=survival -p 19132:19132/udp  abeyuki/minecraft-bedrock-arm64:1.19.81.01
> ```

The docker-compose worked. Thank you very much! Are the environment variables used in the docker-compose the only onces available? Or can I use other minecraft server config variables in there?

**Comment by AbeYuki** [comment]
Yes, the environment variables specified in the docker-compose are only available as Minecraft Bedrock server configuration variables. However, it is possible to specify other configuration variables defined in the server configuration file as environment variables.

In Minecraft Bedrock server, the settings specified in environment variables take precedence over the settings specified in the server.properties file. This means that if a setting is specified in an environment variable, that setting will be applied. However, if no environment variable is set, the server will use the settings specified in the server.properties file.
